version: '3.9'

services:
  lib:
    image: gatsby-source-hashnode:prod
    tty: yes
    working_dir: /usr/src/app/packages/gatsby-source-hashnode
    build:
      context: .
      dockerfile: ./prod.Dockerfile
      args:
        GITHUB_PERSONAL_TOKEN: $GITHUB_PERSONAL_TOKEN 
        GIT_USER_NAME: $GIT_USER_NAME   
        GIT_USER_EMAIL: $GIT_USER_EMAIL   
    

